### ISSUE TITLE
What about local fonts?

### ISSUE THREAD

**Issue by uyriq** [jotyy/Mantine-Admin#11]
![image](https://github.com/jotyy/Mantine-Admin/assets/105006434/40cc777f-3de5-49a9-a4e9-1464194b85c0)
How can we use local fonts ? 
do we need update config to next.config.js?

**Comment by jotyy** [comment]
I've put the local fonts into this file. 
[styles/fonts.ts](https://github.com/jotyy/Mantine-Admin/blob/main/src/styles/%20fonts.ts)

Here's the Next.js official reference: [Fonts](https://nextjs.org/docs/app/api-reference/components/font)
