### ISSUE TITLE
🔥Nice project!  I need it urgently !  Stared !

### ISSUE THREAD

**Issue by asionesjia** [jotyy/Mantine-Admin#8]
Come on !

**Comment by cabbeer** [comment]
Any plans to convert this to Mantine 7?
I can help with the migration. 

...also, agree with OP, amazing work!

**Comment by jotyy** [comment]
> Any plans to convert this to Mantine 7? I can help with the migration.
> 
> ...also, agree with OP, amazing work!

Because I used mantine-react-table to speed up the development of table components in Mantine Admin, but mantine-react-table has not yet been adapted to mantine@7. After mantine-react-table completes the work on version 2, I will migrate to it.

PR always be welcome!👏🏻

**Comment by tijmen61** [comment]
There is now an alpha version for the mantine-react-table by the way.

**Comment by jotyy** [comment]
> There is now an alpha version for the mantine-react-table by the way.

Yes, I'm working on the migration now. A new WIP branch has released.
